/**
 * Root writer prompts for Staging Wiki pages.
 */

import type { WikiRunSpec } from "@okf-wiki/contract";
import type { RunWorkdirLayout } from "../runtime/workdir.js";
import { runWorkdirPromptPaths } from "../runtime/workdir.js";
import { domainList, pageList, type WikiLanguage } from "./system.js";

/**
 * Root writer live user prompt — must drive full Spec concept pages (not stub indexes).
 */
export function rootWritePrompt(input: {
  layout: RunWorkdirLayout;
  spec: WikiRunSpec;
  wikiLanguage?: WikiLanguage;
  multiSource?: boolean;
  receiptIndex?: string;
  repairDefects?: string;
  isRefresh?: boolean;
}): string {
  const paths = runWorkdirPromptPaths(input.layout);
  const lang =
    input.wikiLanguage === "zh"
      ? "Write page titles and body prose in Simplified Chinese. Keep paths, identifiers, and Source Citations untranslated."
      : "Write page titles and body prose in English.";
  const citeForm = input.multiSource
    ? "For multiple repositories: [Source](repo:repository-id/path/to/file#L10-L20). Transform tool path sources/<id>/rest → repo:<id>/rest (never leave sources/ in repo: links)."
    : "For a single repository: [Source](repo:path/to/file#L10-L20). Transform tool path sources/<id>/rest → repo:rest (never leave sources/ in repo: links).";
  const branch = input.isRefresh
    ? "Read skill/references/refresh.md in full (wiki/ already has prior pages)."
    : "Read skill/references/generate.md in full (wiki/ starts empty or fixture-seeded).";
  const receipts =
    input.receiptIndex?.trim() ||
    "Read inputs/evidence/index.json and inputs/evidence/receipts/*.json when present; re-open load-bearing source spans as needed. Do not invent evidence.";
  const repair = input.repairDefects?.trim()
    ? [
        "",
        "## Repair mode",
        "Blocking defects from the review council (fix these issues; do not rewrite unrelated pages unless needed):",
        "Source: inputs/defects.json (when projected) or sealed defects below:",
        input.repairDefects.trim(),
      ].join("\n")
    : "";

  return [
    "You are the Open OKF Wiki Root writer.",
    paths,
    "",
    "## Method",
    "1. Read skill/SKILL.md (job index) in full.",
    `2. ${branch}`,
    "3. Read inputs/spec.json (canonical) or analysis/spec.json (living WikiRunSpec) and follow its pages/domains.",
    "4. Read relevant skill/templates/{overview,architecture,module,flow,concept}.md before writing those page kinds.",
    "5. Use research receipts under inputs/evidence/ before broad source re-scans.",
    "6. Use only tools: ls, find, grep, read, write, edit. Never use bash.",
    "",
    "## Language",
    lang,
    "",
    "## Spec pages (write every critical concept path under wiki/)",
    pageList(input.spec),
    "",
    "## Domains (context)",
    domainList(input.spec),
    "",
    "## Evidence receipts",
    receipts,
    "",
    "## Output contract (OKF v0.2 + product)",
    "- Concept pages (all .md except reserved index.md / log.md): YAML frontmatter with non-empty `type`, `title`, and one-sentence `description`.",
    "  Suggested types: Overview, Architecture, Module, Flow, Concept. Optional `tags` list of short lowercase strings.",
    "- Never write `generated`, `verified`, `stale_after`, or `okf_version` frontmatter — the Run Boundary stamps provenance mechanically at publication.",
    "- Do NOT maintain wiki/**/index.md as a completion criterion. Every directory's index.md is a mechanical progressive-disclosure listing — the product mechanically regenerates every directory index.md after write/repair and again on the publish candidate. Hand-written TOC is not durable authority.",
    "- Do NOT flatten nested pages into a single root listing. Prefer directory structure (modules/, flows/, deeper as needed) for related concepts.",
    "- Narrative entry is overview.md (or Spec path), not index.md. Spec pages must not include index.md or log.md.",
    `- Place verified Source Citations beside facts. ${citeForm}`,
    "- Line numbers must come from read/grep results — never invent ranges.",
    "- Internal links: relative paths ending in .md.",
    "- Cross-link related concept pages.",
    "",
    "When finished, ensure every critical Spec concept path exists on disk under wiki/ (directory layout Spec/Writer owns; indexes are mechanical).",
    repair,
  ].join("\n");
}

export function rootWriteSystemPrompt(): string {
  return [
    "You are the Open OKF Wiki producer agent (Root writer).",
    "Use only the provided tools. Never use bash.",
    "Read skill/SKILL.md before writing. Follow inputs/spec.json (or analysis/spec.json).",
    "Prefer inputs/evidence/ research receipts over re-exploring the whole tree.",
    "Write Staging Wiki concept pages under wiki/. Prefer Spec page paths and directory layout (modules/, flows/).",
    "Concept pages need type + title + description frontmatter. Indexes (**/index.md) are mechanical listings regenerated by the product — not a writer completion criterion.",
    "Never write generated/verified/okf_version frontmatter — the product stamps provenance.",
    "Cite sources with [Source](repo:…) form from real tool line numbers; strip sources/<id>/ from tool paths before citing.",
  ].join(" ");
}
