export {
  type AnalysisReceiptSummary,
  analysisReceiptsDir,
  analysisScratchDir,
  listAnalysisReceipts,
  readAnalysisReceipt,
  safeReceiptNodeId,
  writeAnalysisReceipt,
} from "./analysis-scratch.js";
export { atomicWriteJson } from "./atomic-write.js";
export {
  type CitationRewriteSources,
  type RewriteRepoCitationsOptions,
  relativeSourceHref,
  rewriteOneRepoCitation,
  rewriteRepoCitationsToRelative,
} from "./citation-rewrite.js";
export {
  type AutofixCitationsInContentOptions,
  type AutofixCitationsInContentResult,
  type AutofixWikiTreeResult,
  autofixCitationsInContent,
  autofixWikiTreeCitations,
  type CanonicalizeCitationOptions,
  type CanonicalizeCitationResult,
  type CanonicalizeWikiTreeResult,
  type CitationTargetOptions,
  type CitationTargetParts,
  type ClampCitationOptions,
  type ParseCitationTargetResult,
  canonicalizeCitationInContent,
  canonicalizeCitationTarget,
  canonicalizeWikiTreeCitations,
  clampCitationLineRange,
  countFileLines,
  formatCitationTarget,
  formatRepoCitation,
  parseCitationSourcePath,
  parseCitationTarget,
  parseSourceCitations,
  resolveCitationFile,
  SOURCE_CITATION_RE,
  type SourceCitation,
  type SourceRootMap,
  sourceRootMapFromSources,
  validateCitationFormat,
  validateCitationResolve,
} from "./citations.js";
export {
  type CloneIntoWorkspaceInput,
  type CloneIntoWorkspaceResult,
  cloneIntoWorkspace,
  probeLocalGit,
  WORKSPACE_SOURCES_DIR_NAME,
} from "./git.js";
export {
  createDefaultGitRunner,
  type GitRunner,
  type GitRunResult,
} from "./git-runner.js";
export {
  extractPagesFromMechanicalIssues,
  extractPagesFromValidationMessage,
  extractPathFromValidateError,
  makeMechanicalIssue,
  type MakeMechanicalIssueInput,
  type MechanicalReportSource,
  toMechanicalReport,
} from "./mechanical-report.js";
export {
  OKF_VERSION,
  type OkfStamp,
  type OkfStampTreeResult,
  type OkfVerification,
  stampConceptPage,
  stampRootIndex,
  stampWikiTreeForPublish,
} from "./okf-stamp.js";
export {
  assertAbsolutePath,
  assertContainedPathSafe,
  assertNoSymlinkComponents,
  isPathInside,
  resolveContainedPath,
  resolveExistingDir,
  toPosixRelative,
} from "./paths.js";
export {
  AGENTS_DIR_NAME,
  DEFAULT_PRODUCER_SKILL_NAME,
  defaultServerLogDir,
  homeProducerSkillPath,
  homeSkillsDir,
  isUnderHomeSkills,
  isUnderWorkspaceSkills,
  PRODUCT_LOGS_DIR_NAME,
  productHomeDir,
  SKILLS_DIR_NAME,
  workspaceProducerSkillPath,
  workspaceSkillsDir,
} from "./product-home.js";
export {
  createModelProfile,
  createProviderEntry,
  defaultProviderPath,
  deleteModelProfile,
  deleteProviderEntry,
  loadProviderConfig,
  mutateProviderCatalog,
  PROVIDER_CONFIG_VERSION,
  PROVIDER_FILE_NAME,
  saveProviderConfig,
  setDefaultModelProfile,
  updateModelProfile,
  updateProviderEntry,
} from "./provider-catalog.js";
export {
  maskSecret,
  toModelProfilePublic,
  toProviderEntryPublic,
  toProviderPublic,
} from "./provider-public.js";
export {
  flattenModels,
  getModelProfile,
  hasProviderCredentials,
  mergeHeaders,
  type ResolvedProviderRuntime,
  resolveProviderRuntime,
} from "./provider-runtime.js";
// Publication primitives (ADR 0017 / 0035) — deep modules, no shallow facade.
export {
  type ApplySealedPublicationInput,
  type ApplySealedPublicationResult,
  applySealedPublicationCandidate,
  PublicationConflictError,
  type ReconcilePublicationApplyInput,
  type ReconcilePublicationApplyResult,
  reconcilePublicationApply,
} from "./publication/apply.js";
export {
  digestPublicationTree,
  digestPublicationTreeContentOnly,
  EMPTY_PUBLICATION_DIGEST,
  manifestPublicationTree,
  type PublicationTreeManifest,
} from "./publication/digest.js";
export {
  capturePublicationBaseline,
  withPublicationLock,
} from "./publication/lock.js";
export {
  materializePublicationCandidate,
  type PublishStagingResult,
  rewriteWikiTreeCitationsForPublish,
} from "./publication/materialize.js";
export {
  derivePublishedWikiGraph,
  listPublishedWikiBrowse,
  listPublishedWikiPages,
  PUBLISHED_WIKI_MAX_FILE_BYTES,
  PUBLISHED_WIKI_MAX_PAGES,
  type PublishedWikiBrowse,
  PublishedWikiError,
  type PublishedWikiErrorCode,
  type PublishedWikiPage,
  type PublishedWikiPageSummary,
  readPublishedWikiPage,
} from "./published-wiki.js";
export {
  type FreezeRunBoundaryInput,
  FreezeWikiRunError,
  type FreezeWikiRunErrorCode,
  type FrozenRunBoundary,
  type FrozenSourceSnapshot,
  freezeRunBoundary,
} from "./run-boundary.js";
export {
  analysisDir,
  RUNS_DIR_NAME,
  runSkillDir,
  runsDir,
  runWorkDir,
  WORKSPACE_DIR_NAME,
} from "./run-layout.js";
export {
  listSkillFiles,
  readSkillFrontmatter,
  SKILL_DIGEST_MAX_FILE_BYTES,
  SKILL_DIGEST_MAX_FILES,
  skillDigest,
} from "./skill-digest.js";
export {
  copySkillTree,
  createSkillFork,
  getSkillInfo,
  listSkillDir,
  normalizeSkillRelative,
  readSkillFile,
  skillForkDir,
  writeSkillFile,
  writeWorkspaceSkillFile,
} from "./skill-fork.js";
export {
  ensureHomeProducerSkill,
  type ResolvedSkillSource,
  type ResolveSkillSourceOptions,
  type ResolveWikiSkillPathsInput,
  resolvePackageSkillPath,
  resolveSkillPath,
  resolveSkillSource,
  resolveWikiSkillPaths,
  skillLayoutPaths,
} from "./skill-path.js";
export {
  DEFAULT_SOURCE_IGNORES,
  effectiveIgnoresForSource,
  effectiveSourceIgnores,
  entryMatchesIgnore,
  IGNORE_PRESETS,
  type IgnorePresetId,
  pathMatchesIgnore,
  resolveIgnorePreset,
} from "./source-ignores.js";
export {
  type BoundaryIndex,
  type BoundaryPathEntry,
  type BoundaryPathKind,
  type CoverageCancelledUnit,
  type CoverageInventory,
  type CoverageObligation,
  type CoveragePlan,
  type CoverageSourceRecord,
  type CoverageSurface,
  type CoverageSurfaceEntry,
  type CoverageSurfaceOrigin,
  type CoverageUnit,
  isSurfaceUnitId,
  makeSourceUnit,
  makeSurfaceUnit,
  normalizeSurfacePath,
  parseSurfaceUnitId,
  sourceCoverageUnit,
  sourceUnitId,
  surfaceCoverageUnit,
  surfaceUnitId,
  unitIdForSource,
  unitIdForSurface,
} from "./coverage-types.js";
export {
  BOUNDARY_MAX_ENTRIES_PER_SOURCE,
  buildBoundaryIndex,
  type BuildBoundaryIndexOptions,
  classifyBoundaryPath,
} from "./boundary-index.js";
export {
  buildCoveragePlan,
  type BuildCoveragePlanOptions,
  DEFAULT_MAX_SURFACES_REQUIRED,
  findInventoryUnit,
  SURFACE_COMPLEXITY_THRESHOLD,
} from "./coverage-plan.js";
export {
  buildCoverageInventory,
  type BuildCoverageInventoryOptions,
  INVENTORY_LARGE_FILE_THRESHOLD,
  INVENTORY_MAX_FILES_PER_SOURCE,
  INVENTORY_MAX_SURFACES_PER_SOURCE,
  type InventorySourceInput,
  isPackageManifestName,
  isWorkspaceParentDir,
  PACKAGE_MANIFEST_NAMES,
  toAdaptiveRepositoryInventory,
  WORKSPACE_PARENT_DIRS,
} from "./repository-inventory.js";
export {
  type ValidateWikiOptions,
  type ValidateWikiResult,
  validateCoverageObligations,
  validateCrossSourceFlows,
  validateWikiTree,
  WIKI_VALIDATE_MAX_FILE_BYTES,
  WIKI_VALIDATE_MAX_FILES,
} from "./validate-wiki.js";
export {
  regenerateWikiIndexes,
  renderDirectoryIndex,
  validateWikiIndexes,
  type WikiIndexListEntry,
} from "./wiki-index.js";
export {
  deriveWikiGraph,
  deriveWikiGraphFromTree,
  extractInternalLinkTargets,
  resolveWikiLinkTarget,
  trustTierFromFrontmatter,
  type WikiBrokenLink,
  type WikiGraph,
  type WikiGraphEdge,
  type WikiGraphInputPage,
  type WikiGraphNode,
  type WikiTrustTier,
} from "./wiki-links.js";
export {
  diffWikiPages,
  renderWikiLog,
  stripProvenanceForDiff,
  updateWikiLogForPublish,
  WIKI_LOG_HEADING,
  type WikiLogChange,
} from "./wiki-log.js";
export {
  buildWikiNav,
  parseWikiIndexListing,
  WIKI_NAV_UNLISTED_TITLE,
  type WikiIndexEntry,
  type WikiNavDirNode,
  type WikiNavGroupNode,
  type WikiNavNode,
  type WikiNavPageInput,
  type WikiNavPageNode,
} from "./wiki-nav.js";
export {
  countMarkdownFiles,
  isReservedWikiPath,
  type LoadWikiPageRecordsOptions,
  type LoadWikiPageRecordsResult,
  loadWikiPageRecords,
  parseWikiFrontmatter,
  RESERVED_WIKI_BASENAMES,
  scanWikiTree,
  splitWikiFrontmatter,
  WIKI_MAX_FILE_BYTES,
  type WikiFrontmatter,
  type WikiFrontmatterSplit,
  type WikiPageLoadIssue,
  type WikiPageRecord,
  type WikiTreeFile,
  type WikiTreeIssue,
  type WikiTreeScan,
  wikiMarkdownBody,
} from "./wiki-tree.js";
export {
  APP_STATE_FILE_NAME,
  type AppState,
  DEFAULT_LOAD_HOME_SKILLS,
  defaultAppStatePath,
  getLoadHomeSkills,
  listRecentWorkspaces,
  readAppState,
  registerWorkspaceInAppIndex,
  removeWorkspaceFromAppIndex,
  resolveLoadHomeSkills,
  setLoadHomeSkills,
  writeAppState,
} from "./workspace-app-state.js";
export {
  acquireWikiRunsControlStoreLease,
  acquireWorkspaceActivityLease,
  assertNoWorkspaceActivityLeases,
  assertWorkspaceActive,
  beginWorkspaceDeletion,
  type CreateWorkspaceOptions,
  createWorkspace,
  DEFAULT_MODEL_ID,
  deleteWorkspaceMeta,
  loadWorkspace,
  mutateWorkspace,
  parseResetWikiRunsControlStoreArgs,
  type ResetWikiRunsControlStoreResult,
  registerActiveWorkspaceInAppIndex,
  resetWikiRunsControlStore,
  saveWorkspace,
  WIKI_RUNS_CONTROL_STORE_FILE_NAME,
  WikiRunsControlStoreInUseError,
  type WikiRunsControlStoreLease,
  WORKSPACE_FILE_NAME,
  WORKSPACE_LIFECYCLE_DIR_NAME,
  type WorkspaceActivityLease,
  WorkspaceConfigLockedError,
  WorkspaceDeletedError,
  type WorkspaceDeletionLease,
  WorkspaceLifecycleInUseError,
  type WorkspaceMutation,
  WorkspaceRevisionConflictError,
  withWorkspaceRevision,
  workspaceConfigPath,
  workspaceMetaDir,
} from "./workspace-config.js";
export {
  ProviderStoreError,
  WorkspaceIntakeError,
} from "./workspace-errors.js";
export { resolveWorkspaceModelSelection } from "./workspace-model.js";
export {
  applyWorkspacePatch,
  type ResolveModelSelection,
  type WorkspacePatchDeps,
} from "./workspace-patch.js";
export {
  type AddSourceInput,
  type AddSourceOptions,
  addSource,
  removeSource,
  slugFromPath,
  type UpdateSourceInput,
  uniqueSourceId,
  updateSource,
} from "./workspace-source.js";
export {
  listWorkspaceSummaries,
  loadWorkspaceById,
  type WorkspaceSummary,
} from "./workspace-store.js";
