/**
 * Attempt-local mount: copy sealed sources/skill into workDir,
 * project sealed semantic inputs into inputs/, chmod read-only, path asserts.
 * WikiRuns owns sealing; this mounts + projects the claim envelope.
 *
 * Sealed semantic inputs land under inputs/. analysis/ contains only outputs
 * generated by this Attempt. Transcripts are audit-only and never enter inputs/.
 */

import {
  chmod,
  cp,
  link,
  lstat,
  mkdir,
  readdir,
  readFile,
  rm,
  stat,
  writeFile,
} from "node:fs/promises";
import path from "node:path";
import { parseSealedCoverageInventory, parseSealedCoveragePlan } from "@okf-wiki/contract/coverage";
import type { PiAttemptInput } from "@okf-wiki/contract/pi-attempt";
import {
  type AnalysisReceipt,
  AnalysisReceiptSchema,
  type BoundInput,
  contractForNode,
  ExecutionPlanSchema,
  type FrozenRunManifest,
  FrozenRunManifestSchema,
  type InputRequirement,
  inputRoleMatches,
  WikiRunSpecSchema,
  validateBoundInputs,
} from "@okf-wiki/contract/wiki-runs";
import { isPathInside, safeReceiptNodeId } from "@okf-wiki/core";
import { type RunWorkdirLayout, runWorkdirLayout } from "../workdir.js";
import type { EvidenceBundle, EvidenceBundleEntry } from "./projection.js";

export function assertAttemptPaths(input: PiAttemptInput): void {
  if (!isPathInside(input.attemptDir, input.workDir)) {
    throw new Error("attempt workDir must be inside attemptDir");
  }
  if (!isPathInside(input.attemptDir, input.sessionPath)) {
    throw new Error("attempt sessionPath must be inside attemptDir");
  }
}

function assertSealedSource(input: PiAttemptInput, sourcePath: string): void {
  if (
    !input.sealedInputs.some(
      (item) =>
        item.artifact.kind === "snapshot_set" && isPathInside(item.readOnlyPath, sourcePath),
    )
  ) {
    throw new Error(`source input is not under a sealed snapshot artifact: ${sourcePath}`);
  }
}

function assertSealedSkill(input: PiAttemptInput): void {
  if (
    !input.sealedInputs.some(
      (item) => item.artifact.kind === "skill" && isPathInside(item.readOnlyPath, input.skillPath),
    )
  ) {
    throw new Error("skill input is not under a sealed skill artifact");
  }
}

async function assertOrdinaryTree(directory: string, label: string): Promise<void> {
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const child = path.join(directory, entry.name);
    const info = await lstat(child);
    if (info.isSymbolicLink() || (!info.isDirectory() && !info.isFile())) {
      throw new Error(`${label} contains a non-ordinary filesystem entry: ${child}`);
    }
    if (info.isDirectory()) await assertOrdinaryTree(child, label);
  }
}

async function makeTreeReadOnly(directory: string): Promise<void> {
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const child = path.join(directory, entry.name);
    if (entry.isDirectory()) await makeTreeReadOnly(child);
    else await chmod(child, 0o444);
  }
  await chmod(directory, 0o555);
}

/**
 * Shared sealed read-only source mount (Phase 7).
 * Prefer hardlink tree so each Attempt shares sealed snapshot inodes
 * (O(file count) metadata, not O(bytes) copy). Fall back to full recursive
 * copy when hardlink fails (cross-device, permissions). Skill stays full copy
 * (small). Never introduces symlinks — assertOrdinaryTree still holds.
 */
async function hardlinkTree(from: string, to: string): Promise<void> {
  await mkdir(to, { recursive: true });
  for (const entry of await readdir(from, { withFileTypes: true })) {
    const src = path.join(from, entry.name);
    const dst = path.join(to, entry.name);
    if (entry.isDirectory()) {
      await hardlinkTree(src, dst);
    } else if (entry.isFile()) {
      await link(src, dst);
    } else {
      throw new Error(`non-ordinary entry in sealed tree: ${src}`);
    }
  }
}

async function copyReadOnlyTree(from: string, to: string, label: string): Promise<void> {
  if (!(await stat(from)).isDirectory()) throw new Error(`${label} must be a directory`);
  await assertOrdinaryTree(from, label);
  await cp(from, to, { recursive: true, dereference: false, errorOnExist: true });
  await assertOrdinaryTree(to, label);
  await makeTreeReadOnly(to);
}

/**
 * Mount a sealed source tree into an Attempt workDir.
 * Hardlink-first (shared sealed mount); full copy fallback for correctness.
 *
 * Hardlinked mounts must NOT chmod: hardlinks share inodes with the sealed
 * snapshot, so makeTreeReadOnly would mutate the trusted freeze. Sealed
 * sources are already read-only from freeze materialization.
 */
export async function mountSealedSourceTree(
  from: string,
  to: string,
  label: string,
): Promise<"hardlink" | "copy"> {
  if (!(await stat(from)).isDirectory()) throw new Error(`${label} must be a directory`);
  await assertOrdinaryTree(from, label);
  try {
    await hardlinkTree(from, to);
    await assertOrdinaryTree(to, label);
    // Do not chmod hardlinked trees — would mutate sealed snapshot inodes.
    return "hardlink";
  } catch {
    // Cross-device, link limit, or partial tree: wipe and full-copy (correctness first).
    await rm(to, { recursive: true, force: true }).catch(() => undefined);
    await cp(from, to, { recursive: true, dereference: false, errorOnExist: true });
    await assertOrdinaryTree(to, label);
    await makeTreeReadOnly(to);
    return "copy";
  }
}

/**
 * Resolve a sealed artifact payload.
 * A named payload is required when the role has a fixed artifact shape; a
 * receipt artifact must contain exactly one JSON payload besides its sidecar.
 */
export async function resolveSealedFile(
  readOnlyPath: string,
  preferredNames: string[] = [],
): Promise<string | undefined> {
  try {
    const info = await stat(readOnlyPath);
    if (info.isFile()) return readOnlyPath;
    if (!info.isDirectory()) return undefined;
  } catch {
    return undefined;
  }
  for (const name of preferredNames) {
    const candidate = path.join(readOnlyPath, name);
    try {
      if ((await stat(candidate)).isFile()) return candidate;
    } catch {
      // try next
    }
  }
  if (preferredNames.length > 0) return undefined;
  try {
    const entries = await readdir(readOnlyPath, { withFileTypes: true });
    const jsonFiles = entries
      .filter(
        (e) => e.isFile() && e.name.endsWith(".json") && e.name !== ".okf-artifact-manifest.json",
      )
      .map((e) => e.name)
      .sort();
    return jsonFiles.length === 1 ? path.join(readOnlyPath, jsonFiles[0]!) : undefined;
  } catch {
    return undefined;
  }
}

async function writeReadOnlyFile(target: string, content: string): Promise<void> {
  await mkdir(path.dirname(target), { recursive: true });
  await writeFile(target, content, "utf8");
  await chmod(target, 0o444);
}

/**
 * Project sealed semantic inputs into workDir/inputs/ after sources+skill mount.
 * Fail closed when a required projection target cannot be resolved from a present role.
 */
function mountedInputPath(inputsDir: string, requirement: InputRequirement): string {
  if (!requirement.mountPath) {
    throw new Error(`node input ${requirement.role} has no mounted projection path`);
  }
  return path.join(inputsDir, requirement.mountPath);
}

async function projectSealedInputs(
  input: PiAttemptInput,
  layout: RunWorkdirLayout,
  requirements: readonly InputRequirement[],
): Promise<void> {
  const inputsDir = path.join(input.workDir, "inputs");
  await mkdir(inputsDir, { recursive: true });
  await mkdir(path.join(inputsDir, "evidence", "receipts"), { recursive: true });

  const evidenceEntries: EvidenceBundleEntry[] = [];
  let manifest: FrozenRunManifest | undefined;
  let seededWiki = false;
  const seenRoles = new Set<string>();

  for (const sealed of input.sealedInputs) {
    if (seenRoles.has(sealed.role)) {
      throw new Error(`duplicate sealed input role for ${input.node.key}: ${sealed.role}`);
    }
    seenRoles.add(sealed.role);

    const requirement = requirements.find((candidate) => inputRoleMatches(candidate, sealed.role));
    if (!requirement) {
      throw new Error(`sealed input role is not declared by ${input.node.kind}: ${sealed.role}`);
    }
    if (requirement.artifactKind && sealed.artifact.kind !== requirement.artifactKind) {
      throw new Error(
        `sealed input ${sealed.role} for ${input.node.key} has kind ${sealed.artifact.kind}; ` +
          `expected ${requirement.artifactKind}`,
      );
    }
    if (requirement.projection === "audit-only" || requirement.projection === "handle") continue;

    if (requirement.role === "sources" || requirement.role === "skill") continue;

    if (requirement.role === "spec") {
      const file = await resolveSealedFile(sealed.readOnlyPath, ["spec.json"]);
      if (!file) throw new Error("sealed spec artifact does not contain a readable spec.json");
      const raw = await readFile(file, "utf8");
      await writeReadOnlyFile(
        mountedInputPath(inputsDir, requirement),
        raw.endsWith("\n") ? raw : `${raw}\n`,
      );
      continue;
    }

    if (requirement.role === "execution_plan") {
      const file = await resolveSealedFile(sealed.readOnlyPath, ["execution-plan.json"]);
      if (!file) throw new Error("sealed execution_plan artifact is unreadable");
      const raw = await readFile(file, "utf8");
      ExecutionPlanSchema.parse(JSON.parse(raw));
      await writeReadOnlyFile(
        mountedInputPath(inputsDir, requirement),
        raw.endsWith("\n") ? raw : `${raw}\n`,
      );
      continue;
    }

    if (requirement.role === "frozen_run_manifest") {
      const file = await resolveSealedFile(sealed.readOnlyPath, ["frozen-run-manifest.json"]);
      if (!file) throw new Error("sealed frozen_run_manifest is unreadable");
      const raw = await readFile(file, "utf8");
      try {
        manifest = FrozenRunManifestSchema.parse(JSON.parse(raw));
      } catch (error) {
        throw new Error(
          `sealed frozen_run_manifest is invalid: ${error instanceof Error ? error.message : String(error)}`,
        );
      }
      if (manifest.mode !== manifest.intent.mode) {
        throw new Error("sealed frozen_run_manifest mode must match intent.mode");
      }
      await writeReadOnlyFile(
        mountedInputPath(inputsDir, requirement),
        raw.endsWith("\n") ? raw : `${raw}\n`,
      );
      await writeReadOnlyFile(
        path.join(inputsDir, "intent.json"),
        `${JSON.stringify(manifest.intent, null, 2)}\n`,
      );
      continue;
    }

    if (requirement.role === "defects") {
      const file = await resolveSealedFile(sealed.readOnlyPath, ["defects.json"]);
      if (!file) throw new Error("sealed defects artifact is unreadable");
      const raw = await readFile(file, "utf8");
      await writeReadOnlyFile(
        mountedInputPath(inputsDir, requirement),
        raw.endsWith("\n") ? raw : `${raw}\n`,
      );
      continue;
    }

    if (requirement.role === "mechanical_report") {
      const file = await resolveSealedFile(sealed.readOnlyPath, ["validate-report.json"]);
      if (!file) throw new Error("sealed mechanical_report artifact is unreadable");
      const raw = await readFile(file, "utf8");
      await writeReadOnlyFile(
        mountedInputPath(inputsDir, requirement),
        raw.endsWith("\n") ? raw : `${raw}\n`,
      );
      continue;
    }

    if (requirement.role === "operator_input") {
      const file = await resolveSealedFile(sealed.readOnlyPath, ["operator-input.json"]);
      if (!file) throw new Error("sealed operator_input artifact is unreadable");
      const raw = await readFile(file, "utf8");
      await writeReadOnlyFile(
        mountedInputPath(inputsDir, requirement),
        raw.endsWith("\n") ? raw : `${raw}\n`,
      );
      continue;
    }

    if (requirement.role === "prior_spec") {
      const file = await resolveSealedFile(sealed.readOnlyPath, [
        "prior-spec.json",
        "spec.json",
      ]);
      if (!file) throw new Error("sealed prior_spec artifact does not contain a readable Spec");
      const raw = await readFile(file, "utf8");
      // Validate shape so revise cannot bind garbage as prior Spec.
      WikiRunSpecSchema.parse(JSON.parse(raw));
      await writeReadOnlyFile(
        mountedInputPath(inputsDir, requirement),
        raw.endsWith("\n") ? raw : `${raw}\n`,
      );
      continue;
    }

    if (requirement.role === "coverage_inventory") {
      const file = await resolveSealedFile(sealed.readOnlyPath, [
        "coverage-inventory.json",
        "inventory.json",
      ]);
      if (!file) throw new Error("sealed coverage_inventory artifact is unreadable");
      const raw = await readFile(file, "utf8");
      const json = JSON.parse(raw) as unknown;
      // Freeze inventory includes host extras; strip via shared sealed parser.
      if (!parseSealedCoverageInventory(json)) {
        throw new Error(
          "sealed coverage_inventory must be contract/host inventory with sources[]",
        );
      }
      await writeReadOnlyFile(
        mountedInputPath(inputsDir, requirement),
        raw.endsWith("\n") ? raw : `${raw}\n`,
      );
      continue;
    }

    if (requirement.role === "coverage_plan") {
      const file = await resolveSealedFile(sealed.readOnlyPath, [
        "coverage-plan.json",
        "plan.json",
      ]);
      if (!file) throw new Error("sealed coverage_plan artifact is unreadable");
      const raw = await readFile(file, "utf8");
      const json = JSON.parse(raw) as unknown;
      // Freeze plan includes host extras (lightPath/reasons/maxSurfacesRequired).
      // Strict CoveragePlanSchema rejects them — use shared sealed parser.
      if (!parseSealedCoveragePlan(json)) {
        throw new Error(
          "sealed coverage_plan must be contract { requiredUnits } or legacy core { required }",
        );
      }
      await writeReadOnlyFile(
        mountedInputPath(inputsDir, requirement),
        raw.endsWith("\n") ? raw : `${raw}\n`,
      );
      continue;
    }

    if (requirement.role === "boundary_index") {
      const file = await resolveSealedFile(sealed.readOnlyPath, [
        "boundary-index.json",
        "boundaries.json",
      ]);
      if (!file) throw new Error("sealed boundary_index artifact is unreadable");
      const raw = await readFile(file, "utf8");
      // Path-list only; soft-validate shape without a hard schema dependency.
      const parsed = JSON.parse(raw) as { version?: unknown; entries?: unknown };
      if (parsed?.version !== 1 || !Array.isArray(parsed.entries)) {
        throw new Error("sealed boundary_index must be { version: 1, entries: [...] }");
      }
      await writeReadOnlyFile(
        mountedInputPath(inputsDir, requirement),
        raw.endsWith("\n") ? raw : `${raw}\n`,
      );
      continue;
    }

    if (requirement.role === "research") {
      const file = await resolveSealedFile(sealed.readOnlyPath, []);
      if (!file) {
        throw new Error(`sealed research receipt is unreadable for role ${sealed.role}`);
      }
      const raw = await readFile(file, "utf8");
      let receipt: AnalysisReceipt | undefined;
      try {
        receipt = AnalysisReceiptSchema.parse(JSON.parse(raw));
      } catch {
        // Still project bytes; index uses best-effort fields when schema fails.
      }
      const nodeId =
        receipt?.nodeId ??
        sealed.role.replace(/:research$/, "").replace(/^research$/, sealed.artifact.artifactId);
      const safe = safeReceiptNodeId(nodeId);
      const destName = `${safe}.json`;
      const destPath = path.join(mountedInputPath(inputsDir, requirement), destName);
      await writeReadOnlyFile(destPath, raw.endsWith("\n") ? raw : `${raw}\n`);
      evidenceEntries.push({
        handle: sealed.artifact.artifactId,
        path: `inputs/evidence/receipts/${destName}`,
        digest: sealed.artifact.digest,
        scope: receipt?.scope ?? "",
        summary: (receipt?.summary ?? "").slice(0, 500),
        findingsCount: receipt?.findings?.length ?? 0,
        nodeId,
        role: sealed.role,
      });
      continue;
    }

    if (requirement.role === "prior_wiki" || requirement.role === "wiki_tree") {
      // Mount read-only copy under inputs/prior-wiki/ when present.
      const priorMount = mountedInputPath(inputsDir, requirement);
      try {
        const info = await stat(sealed.readOnlyPath);
        if (info.isDirectory()) {
          // Only create prior-wiki mount once (prefer prior_wiki role over wiki_tree).
          if (requirement.role === "prior_wiki" || !(await dirExists(priorMount))) {
            if (await dirExists(priorMount)) {
              // Replace only when upgrading from wiki_tree to prior_wiki — skip if already prior.
            } else {
              await copyReadOnlyTree(sealed.readOnlyPath, priorMount, `sealed ${sealed.role}`);
            }
          }
          // Seed writable wiki/ for refresh / repair when not already seeded.
          if (!seededWiki) {
            const wikiEmpty = await isDirEmpty(layout.wikiDir);
            if (wikiEmpty) {
              await cp(sealed.readOnlyPath, layout.wikiDir, {
                recursive: true,
                dereference: false,
                errorOnExist: false,
              });
              seededWiki = true;
            }
          }
        }
      } catch (error) {
        throw new Error(
          `sealed ${sealed.role} wiki tree is unreadable: ${error instanceof Error ? error.message : String(error)}`,
        );
      }
      continue;
    }

    throw new Error(`unsupported mounted projection role: ${requirement.role}`);
  }

  if (!manifest) {
    throw new Error(`node ${input.node.key} is missing a valid frozen_run_manifest projection`);
  }

  // Evidence index (always written so consumers have a stable path).
  const bundle: EvidenceBundle = {
    receipts: evidenceEntries.sort((a, b) => a.nodeId.localeCompare(b.nodeId)),
  };
  await writeReadOnlyFile(
    path.join(inputsDir, "evidence", "index.json"),
    `${JSON.stringify(bundle, null, 2)}\n`,
  );

  // Refresh fail-closed: mode refresh requires prior wiki projection.
  if (manifest.intent.mode === "refresh") {
    const hasPrior =
      (await dirExists(path.join(inputsDir, "prior-wiki"))) ||
      input.sealedInputs.some((s) => s.role === "prior_wiki" || s.role === "wiki_tree");
    if (!hasPrior) {
      throw new Error(
        "refresh mode requires a sealed prior_wiki (or wiki_tree) input; freeze must pin the published wiki",
      );
    }
  }

  // Mark inputs tree read-only at the root (files already 0444).
  try {
    await chmod(path.join(inputsDir, "evidence"), 0o555);
    await chmod(path.join(inputsDir, "evidence", "receipts"), 0o555);
    await chmod(inputsDir, 0o555);
  } catch {
    // best-effort on platforms that restrict dir chmod
  }
}

async function dirExists(target: string): Promise<boolean> {
  try {
    return (await stat(target)).isDirectory();
  } catch {
    return false;
  }
}

async function isDirEmpty(directory: string): Promise<boolean> {
  try {
    const entries = await readdir(directory);
    return entries.length === 0;
  } catch {
    return true;
  }
}

/** Mount sealed sources + skill under workDir; project semantic inputs; create wiki/analysis. */
export async function materializeInputs(input: PiAttemptInput): Promise<RunWorkdirLayout> {
  assertAttemptPaths(input);
  const contract = contractForNode(input.node.kind, input.node.key);
  if (contract.execution !== "pi") {
    throw new Error(`cannot materialize non-Pi WikiRuns node: ${input.node.kind}`);
  }
  validateBoundInputs(
    contract,
    input.sealedInputs.map(
      (sealed): BoundInput => ({ role: sealed.role, kind: sealed.artifact.kind }),
    ),
  );
  await mkdir(input.workDir, { recursive: true });
  const sourceMounts = new Map<string, string>();
  for (const [sourceId, sourcePath] of Object.entries(input.sourcePaths)) {
    assertSealedSource(input, sourcePath);
    const mount = path.join(input.workDir, "sources", sourceId);
    await mkdir(path.dirname(mount), { recursive: true });
    // Phase 7: shared sealed read-only source mount (hardlink; copy fallback).
    await mountSealedSourceTree(sourcePath, mount, `sealed source ${sourceId}`);
    sourceMounts.set(sourceId, mount);
  }
  assertSealedSkill(input);
  // Skill is small; full copy keeps isolation simple.
  await copyReadOnlyTree(input.skillPath, path.join(input.workDir, "skill"), "sealed skill");
  await mkdir(path.join(input.workDir, "wiki"), { recursive: true });
  await mkdir(path.join(input.workDir, "analysis"), { recursive: true });
  const layout = runWorkdirLayout(input.workDir, sourceMounts);
  await projectSealedInputs(input, layout, contract.requiredInputs);
  return layout;
}
