/**
 * HTTP transport for the operator Web UI.
 * Domain types come from `@okf-wiki/contract` — do not redeclare schemas here.
 *
 * Barrel re-exports keep `from "../api"` / `from "../../api"` working after the split.
 */

export {
  type AgentCommand,
  type AgentCommandResponse,
  type AgentSseEvent,
  agentSessionCommand,
  agentSessionEventsUrl,
  type CreatePiAgentSessionBody,
  createAgentSession,
  deleteAgentSession,
  listAgentSessions,
  listOperatorCommands,
  type PiSessionSummary,
  parseAgentSessionEvent,
} from "./agent-sessions";
export {
  ApiError,
  getApiBase,
  hasApiErrorCode,
  messageFromErrorBody,
  request,
} from "./client";
export {
  type AppSettingsPublic,
  createModelProfile,
  createProvider,
  type DoctorResponse,
  deleteModelProfile,
  deleteProvider,
  getAppSettings,
  getDoctor,
  getHealth,
  getProvider,
  type HealthResponse,
  type ModelProfilePublic,
  type ModelProfileWriteInput,
  type ProviderApiShape,
  type ProviderEntryPublic,
  type ProviderEntryWriteInput,
  type ProviderPublic,
  type ProviderTestResult,
  patchAppSettings,
  setDefaultModelProfile,
  testProvider,
  updateModelProfile,
  updateProvider,
} from "./provider";
export {
  getWikiGraph,
  getWikiPage,
  listWikiPages,
  type WikiGraphNode,
  type WikiGraphResponse,
  type WikiNavNode,
  type WikiPageListResponse,
  type WikiPageResponse,
  type WikiPageSummary,
} from "./wiki";
export {
  dispatchWikiRunCommand,
  getCandidateDiff,
  getCandidatePage,
  getCandidateTree,
  getRunIndex,
  getWikiRun,
  getWikiRunAttemptTranscript,
  getWikiRunSpec,
  type WikiRunAttemptTranscript,
  type WikiRunListItem,
  type WikiRunState,
  wikiRunAttemptTranscriptEventsUrl,
  wikiRunEventsUrl,
  wikiRunIndexEventsUrl,
} from "./wiki-runs";
export {
  parseWikiRunEvent,
  parseWikiRunIndexEvent,
  parseWikiRunSnapshotEvent,
} from "./wiki-runs-events";
export {
  type AddSourceInput,
  addSource,
  type CloneSourceInput,
  type CreateWorkspaceInput,
  cloneSource,
  createWorkspace,
  createWorkspaceSkillFork,
  deleteSource,
  deleteWorkspace,
  type GitProbe,
  getWorkspace,
  getWorkspaceSkill,
  listWorkspaceSkillFiles,
  listWorkspaces,
  type PatchWorkspaceInput,
  patchWorkspace,
  probeSources,
  readWorkspaceSkillFile,
  resetWorkspaceSkill,
  type SkillFileContent,
  type SkillFileEntry,
  type SkillInfo,
  type SourceOrigin,
  type SourceProbeResult,
  type UpdateSourceInput,
  updateSource,
  type WikiLanguage,
  type WorkspaceConfig,
  type WorkspaceSource,
  type WorkspaceSummary,
  workspaceFromRevisionConflict,
  writeWorkspaceSkillFile,
} from "./workspaces";
