/** Operator AgentMessage wire shape + pure Pi content parsers (W1). */

export {
  type AdaptiveRouterDecision,
  type AdaptiveRouterInput,
  planUncertaintyFromSpec,
  type RepositoryInventory,
  resolveAdaptiveOrchestration,
} from "./adaptive-router.js";
export {
  type AgentContentPart,
  AgentContentPartSchema,
  type AgentMessage,
  type AgentMessageRole,
  AgentMessageRoleSchema,
  AgentMessageSchema,
  type AgentMessageStatus,
  AgentMessageStatusSchema,
  type AgentThinkingStatus,
  AgentThinkingStatusSchema,
  type AgentToolCall,
  AgentToolCallSchema,
  type AgentToolCallStatus,
  AgentToolCallStatusSchema,
  assistantFromSnapshot,
  extractAssistantError,
  extractMessageText,
  extractMessageThinking,
  extractPartsFromMessage,
  extractToolCallsFromMessage,
  finalizeIncompleteTools,
  finalizeIncompleteToolsOnMessage,
  formatToolResultText,
  isRecord,
  makeId,
  messageRole,
  PAYLOAD_TEXT_MAX,
  patchToolsOnAssistant,
  piMessageId,
  projectAgentMessagesFromPiHistory,
  toolOutputFromResult,
  wikiProduceDetails,
} from "./agent-message.js";
/** Pi Operator Session commands and genuine-event SSE envelope (ADR 0032). */
export {
  type AgentAbortCommand,
  type AgentAbortCompactionCommand,
  type AgentClearQueueCommand,
  type AgentCommand,
  type AgentCommandResponse,
  AgentCommandSchema,
  type AgentCompactCommand,
  type AgentFollowUpCommand,
  type AgentPromptCommand,
  type AgentSetModelCommand,
  type AgentSseEvent,
  AgentSseEventSchema,
  type AgentSseHeartbeat,
  type AgentSseSnapshot,
  type AgentSseStream,
  AgentSseStreamSchema,
  type AgentSteerCommand,
  type CreatePiAgentSessionBody,
  CreatePiAgentSessionBodySchema,
  type CreatePiAgentSessionResponse,
  PI_SESSIONS_DIR,
  type PiSessionSummary,
  parseAgentCommand,
  safeParseAgentCommand,
} from "./agent-protocol.js";
/** Live stream reduce + view patches (server-owned projection). */
export {
  type AgentStreamViewPatch,
  AgentStreamViewPatchSchema,
  applySnapshotWithActiveTool,
  applyStreamPatch,
  type ContextPhase,
  ContextPhaseSchema,
  createPiStreamState,
  deriveContextPhase,
  diffStreamState,
  finalizeIncompleteToolsInState,
  type PiAgentStatus,
  PiAgentStatusSchema,
  type PiStreamState,
  reducePiEvent,
  updateToolInState,
  viewMessages,
} from "./agent-stream.js";
export {
  PROVIDER_STORE_ERROR_CODES,
  type ProviderStoreErrorCode,
  WORKSPACE_INTAKE_ERROR_CODES,
  type WorkspaceIntakeErrorCode,
} from "./errors.js";
/** Candidate evaluation / mechanical validate / repair policy (Wiki workflow Phase 1). */
export {
  type EvaluationOnExhausted,
  EvaluationOnExhaustedSchema,
  type EvaluationPolicy,
  type EvaluationPolicyOverrides,
  EvaluationPolicyOverridesSchema,
  EvaluationPolicySchema,
  evaluationPolicyFromAcceptance,
  type MechanicalAutoFixPolicy,
  MechanicalAutoFixPolicySchema,
  type MechanicalEvaluationPolicy,
  MechanicalEvaluationPolicySchema,
  type MechanicalFixHint,
  MechanicalFixHintSchema,
  type MechanicalIssue,
  type MechanicalIssueCode,
  MechanicalIssueCodeSchema,
  MechanicalIssueSchema,
  type MechanicalReport,
  MechanicalReportSchema,
  type RepairIssue,
  RepairIssueSchema,
  type RepairRequest,
  RepairRequestSchema,
  type RepairScope,
  type RepairScopeMode,
  RepairScopeModeSchema,
  RepairScopeSchema,
  type RepairSource,
  RepairSourceSchema,
  type SemanticEvaluationPolicy,
  SemanticEvaluationPolicySchema,
  type WikiCandidate,
  type WikiCandidateProducedBy,
  WikiCandidateProducedBySchema,
  WikiCandidateSchema,
} from "./evaluation.js";
export {
  type SourceAdd,
  SourceAddSchema,
  type SourceClone,
  SourceCloneSchema,
  type SourceUpdate,
  SourceUpdateSchema,
  type WorkspaceCreate,
  WorkspaceCreateSchema,
  type WorkspacePatch,
  type WorkspacePatchRequest,
  WorkspacePatchRequestSchema,
  WorkspacePatchSchema,
  type WorkspaceRevisionRequest,
  WorkspaceRevisionRequestSchema,
} from "./intake.js";
export {
  allNodeContracts,
  type BoundInput,
  contractForNode,
  type InputRequirement,
  inputRoleMatches,
  isResearchRole,
  isReviewSeatRole,
  metricsRoleForNodeKind,
  type NodeContract,
  type OutputRequirement,
  type ProducedArtifact,
  type ProjectionMode,
  roleSatisfied,
  validateBoundInputs,
  validateNodeOutputs,
} from "./node-contract.js";
export {
  type LocalAbsolutePath,
  LocalAbsolutePathSchema,
  type PiAttemptArtifactDescriptor,
  PiAttemptArtifactDescriptorSchema,
  type PiAttemptExecutor,
  type PiAttemptFailureClass,
  PiAttemptFailureClassSchema,
  type PiAttemptInput,
  type PiAttemptInputArtifact,
  PiAttemptInputArtifactSchema,
  PiAttemptInputSchema,
  type PiAttemptNode,
  type PiAttemptNodeDetail,
  PiAttemptNodeDetailSchema,
  PiAttemptNodeSchema,
  type PiAttemptOutcome,
  PiAttemptOutcomeSchema,
  type PiAttemptTranscriptDescriptor,
  PiAttemptTranscriptDescriptorSchema,
} from "./pi-attempt.js";
export {
  type GitObjectId,
  GitObjectIdSchema,
  type Sha256Hex,
  Sha256HexSchema,
} from "./primitives.js";
export {
  type CatalogModel,
  CatalogModelSchema,
  type ModelProfile,
  type ModelProfilePublic,
  ModelProfilePublicSchema,
  ModelProfileSchema,
  type ModelProfileWrite,
  ModelProfileWriteSchema,
  OPENAI_COMPATIBLE_PROVIDER_KIND,
  type ProviderApiShape,
  ProviderApiShapeSchema,
  type ProviderConfig,
  ProviderConfigSchema,
  type ProviderEntry,
  type ProviderEntryPublic,
  ProviderEntryPublicSchema,
  ProviderEntrySchema,
  type ProviderEntryWrite,
  ProviderEntryWriteSchema,
  type ProviderHeaders,
  ProviderHeadersSchema,
  type ProviderKind,
  ProviderKindSchema,
  type ProviderPublic,
  ProviderPublicSchema,
  type ProviderTestResult,
  ProviderTestResultSchema,
} from "./provider.js";
export {
  type AnalysisReceipt,
  AnalysisReceiptSchema,
  type ReceiptStatus,
  ReceiptStatusSchema,
} from "./receipt.js";
export {
  type DefectItem,
  DefectItemSchema,
  type DefectReport,
  DefectReportSchema,
  type DefectSeverity,
  DefectSeveritySchema,
  defaultWikiRunSpec,
  type ExecutionPlan,
  type ExecutionPlanDelta,
  ExecutionPlanDeltaSchema,
  type ExecutionPlanDeltaWorkUnit,
  ExecutionPlanDeltaWorkUnitSchema,
  ExecutionPlanSchema,
  type ExecutionPlanWorkUnit,
  ExecutionPlanWorkUnitSchema,
  type FrozenRunManifest,
  FrozenRunManifestSchema,
  type MergedDefectReport,
  MergedDefectReportSchema,
  type RepositorySnapshot,
  RepositorySnapshotSchema,
  SUBMIT_DEFECT_REPORT_TOOL_NAME,
  SUBMIT_WIKI_RUN_SPEC_TOOL_NAME,
  type WikiPageTemplate,
  WikiPageTemplateSchema,
  type WikiRunSpec,
  type WikiRunSpecAcceptance,
  WikiRunSpecAcceptanceSchema,
  type WikiRunSpecDomain,
  WikiRunSpecDomainSchema,
  type WikiRunSpecPage,
  WikiRunSpecPageSchema,
  WikiRunSpecSchema,
  type WikiSpec,
  WikiSpecSchema,
} from "./run.js";
export {
  type AttemptItem,
  AttemptItemSchema,
  type AttemptRole,
  AttemptRoleSchema,
  type AttemptTraceEvent,
  AttemptTraceEventSchema,
  type ErrorClass,
  ErrorClassSchema,
  type GraphNodeKind,
  GraphNodeKindSchema,
  type NodeAttempt,
  NodeAttemptSchema,
  type NodeAttemptStatus,
  NodeAttemptStatusSchema,
} from "./run-graph.js";
export {
  WIKI_PRODUCE_RECEIPT_STATUSES,
  type WikiProduceReceiptStatus,
  type WikiProduceToolStatus,
  WikiProduceToolStatusSchema,
} from "./run-phase.js";
/** Browser-safe Operator Session wire projection (ADR 0039). */
export {
  applySessionStreamPatch,
  createSessionStreamState,
  diffSessionStreamState,
  type SessionMessage,
  type SessionMessageRole,
  SessionMessageRoleSchema,
  SessionMessageSchema,
  type SessionMessageStatus,
  SessionMessageStatusSchema,
  type SessionStreamPatch,
  SessionStreamPatchSchema,
  type SessionStreamState,
  SessionStreamStateSchema,
  type SessionTool,
  SessionToolSchema,
  viewSessionMessages,
} from "./session-stream.js";
/** Ephemeral Operator Session context-fill (UI only; not control truth). */
export {
  buildSessionUsage,
  type ContextFillView,
  contextFillPercent,
  extractContextTokensFromPiHistory,
  extractContextTokensFromPiMessage,
  formatContextFill,
  formatTokenCount,
  type SessionUsage,
  SessionUsageSchema,
} from "./session-usage.js";
export {
  type SkillFileContent,
  SkillFileContentSchema,
  type SkillFileEntry,
  SkillFileEntrySchema,
  type SkillInfo,
  SkillInfoSchema,
  type SkillSourceKind,
  SkillSourceKindSchema,
} from "./skill.js";
export {
  type WikiProduceToolDetails,
  WikiProduceToolDetailsSchema,
} from "./wiki-produce.js";
export {
  type AttemptMetrics,
  AttemptMetricsSchema,
  type CancelRunCommand,
  CancelRunCommandSchema,
  type CandidateDiffRead,
  CandidateDiffReadSchema,
  CandidatePagePathSchema,
  type CandidatePageRead,
  CandidatePageReadSchema,
  type CandidateTreeRead,
  CandidateTreeReadSchema,
  type ContinueEvaluationCommand,
  ContinueEvaluationCommandSchema,
  type CreateReviewThreadCommand,
  CreateReviewThreadCommandSchema,
  ExpectedControlRevisionSchema,
  type FixGateDecision,
  FixGateDecisionSchema,
  type PauseRunCommand,
  PauseRunCommandSchema,
  type RequestRepairCommand,
  RequestRepairCommandSchema,
  type RerunNodeCommand,
  RerunNodeCommandSchema,
  type ResolveGateCommand,
  ResolveGateCommandSchema,
  type ResolveReviewThreadCommand,
  ResolveReviewThreadCommandSchema,
  type ResumeRunCommand,
  ResumeRunCommandSchema,
  type RetryFailedNodeCommand,
  RetryFailedNodeCommandSchema,
  type ReviewThread,
  type ReviewThreadId,
  ReviewThreadIdSchema,
  ReviewThreadSchema,
  type ReviewThreadState,
  ReviewThreadStateSchema,
  type RunCommand,
  type RunCommandContext,
  RunCommandContextSchema,
  type RunCommandId,
  RunCommandIdSchema,
  type RunCommandKey,
  RunCommandKeySchema,
  type RunCommandReceipt,
  RunCommandReceiptSchema,
  RunCommandSchema,
  type RunIntent,
  RunIntentSchema,
  type RunRevision,
  type RunRevisionId,
  RunRevisionIdSchema,
  RunRevisionSchema,
  type StartRunCommand,
  StartRunCommandSchema,
  type SubmitRunRevisionCommand,
  SubmitRunRevisionCommandSchema,
  WIKI_RUNS_SCHEMA,
  type WikiRunArtifact,
  type WikiRunArtifactKind,
  WikiRunArtifactKindSchema,
  WikiRunArtifactSchema,
  type WikiRunAttempt,
  WikiRunAttemptSchema,
  type WikiRunAttemptState,
  WikiRunAttemptStateSchema,
  type WikiRunAttemptTranscript,
  type WikiRunAttemptTranscriptDoneFrame,
  WikiRunAttemptTranscriptDoneFrameSchema,
  type WikiRunAttemptTranscriptErrorFrame,
  WikiRunAttemptTranscriptErrorFrameSchema,
  WikiRunAttemptTranscriptSchema,
  type WikiRunAttemptTranscriptTraceFrame,
  WikiRunAttemptTranscriptTraceFrameSchema,
  type WikiRunCandidate,
  WikiRunCandidateSchema,
  type WikiRunCommandResponse,
  WikiRunCommandResponseSchema,
  type WikiRunDefinitionVersion,
  WikiRunDefinitionVersionSchema,
  type WikiRunEffect,
  WikiRunEffectSchema,
  type WikiRunEffectState,
  WikiRunEffectStateSchema,
  type WikiRunEvaluationRecovery,
  WikiRunEvaluationRecoverySchema,
  type WikiRunEvent,
  WikiRunEventSchema,
  type WikiRunEventType,
  WikiRunEventTypeSchema,
  type WikiRunGate,
  type WikiRunGateDecisionValue,
  WikiRunGateDecisionValueSchema,
  type WikiRunGateDetail,
  WikiRunGateDetailSchema,
  type WikiRunGateKind,
  WikiRunGateKindSchema,
  WikiRunGateSchema,
  type WikiRunGateState,
  WikiRunGateStateSchema,
  type WikiRunGetResponse,
  WikiRunGetResponseSchema,
  type WikiRunId,
  WikiRunIdSchema,
  type WikiRunIndexEvent,
  WikiRunIndexEventSchema,
  type WikiRunIndexGetResponse,
  WikiRunIndexGetResponseSchema,
  type WikiRunListItem,
  WikiRunListItemSchema,
  type WikiRunNode,
  type WikiRunNodeDetail,
  WikiRunNodeDetailSchema,
  type WikiRunNodeKind,
  WikiRunNodeKindSchema,
  WikiRunNodeSchema,
  type WikiRunNodeState,
  WikiRunNodeStateSchema,
  type WikiRunSnapshot,
  WikiRunSnapshotSchema,
  type WikiRunSpecRead,
  WikiRunSpecReadSchema,
  type WikiRunState,
  WikiRunStateSchema,
  type WorkspaceId,
  WorkspaceIdSchema,
} from "./wiki-runs.js";
export {
  DEFAULT_OPERATOR_TOOLS,
  DEFAULT_ORCHESTRATION,
  type GitProbe,
  GitProbeSchema,
  IGNORE_PRESETS,
  IgnorePatternSchema,
  type ModelRef,
  ModelRefSchema,
  type OperatorToolName,
  OperatorToolNameSchema,
  OperatorToolsSchema,
  type RetryLimits,
  RetryLimitsSchema,
  type RetryProviderLimits,
  RetryProviderLimitsSchema,
  resolveOrchestration,
  SourceIdSchema,
  type SourceOrigin,
  SourceOriginSchema,
  type WikiLanguage,
  WikiLanguageSchema,
  type WorkspaceConfig,
  WorkspaceConfigSchema,
  type WorkspaceLimits,
  type WorkspaceLimitsPatch,
  WorkspaceLimitsPatchSchema,
  WorkspaceLimitsSchema,
  type WorkspaceOrchestration,
  WorkspaceOrchestrationSchema,
  WorkspaceRevisionSchema,
  type WorkspaceRoleModels,
  WorkspaceRoleModelsSchema,
  type WorkspaceSource,
  WorkspaceSourceSchema,
  type WorkspaceSummary,
  WorkspaceSummarySchema,
} from "./workspace.js";
